### PR TITLE
Website is going into production.

### PR DESCRIPTION
**Pull request by dashinay**
Pushing the dev branch into the prod. Travis Ci Prod env deployment.

### CODE REVIEW

**Review by erikNeville — APPROVED** [review]
Looks like you got it down. Merging dev into prod.

**Review by erikNeville — CHANGES_REQUESTED** [review]
This needs to use our most recently merged files/folders in the dev branch

**Comment by dashinay** [comment]
I have checked the pull request and it does include the latest merges which are there. Can you check if everything is correct.

**Review by erikNeville — APPROVED** [review]
All up to date. Thanks @dashinay

**Review by hkhual — APPROVED** [review]
tested and everything is working now.

**Review by yahya09206 — APPROVED** [review]
running on my local machine, looks good

**Pull request merged**
