### PR TITLE
Add filter to dashboard with fuse

### PR DESCRIPTION
**Pull request by coultergeist**
- Add additional commenting on fuse incorporation
- Left original filter `for loop` in case client wants to revert at any time
- Updated API call
- Cleaned up "search bar" to appear under `delete` button
- Search/filter function is working properly with "dynamic searching" 

Screen Shot 2019-03-19 at 5 44 41 PM

### CODE REVIEW

**Review by hkhual — COMMENTED** [review]
I like the search bar and its delete button. For some reason, the search function isn't working on my machine. When i pressed the delete button, it refreshed and went into sign in page.

**Review by erikNeville — APPROVED** [review]
I like it.

**Comment by coultergeist** [comment]
@hkhual The delete button (the pink X "cancel" box) error is a redirect error though I'm not sure whose. At the `if(!auth) return <Redirect to='/' />` (line 100 on `Dashboard.js`) the redirect will call the dashboard when it's corrected. The filter function is working, which is what this PR is concerned with.

To test the filter function, simply type in the search bar. You do not need to press enter, it's a dynamic search. To clear you only press the delete key on your keyboard.

You will see I just call the redirect that previously existed. View in the files changed and see I didn't manipulate that call.

**Review by hkhual — APPROVED** [review]
@coultergeist  saw your comment. I think the the problem has do with Auth.currentSession() method since we use this method to Load the State from the Session. Other than that, the design Looks good.

**Comment by coultergeist** [comment]
@hkhual I created a bug for that issue [#120 Bug: Redirect call not functioning](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/120) as this was part of your Sprint 4 task.

**Pull request merged**
